myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.carrinho_detail, name='cart_detail'),
    path('add/<produto_id>/', views.adiciona_carrinho, name='cart_add'),
    path('remove/<produto_id>/', views.deleta_do_carrinho, name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('carrinho/', include('cart.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.lista_produtos, name='lista_produtos'),
    path('<slug_categoria>/', views.lista_produtos, name='lista_produtos_categoria'),
    path('<id>/<slug>/', views.detalhe_produto, name='detalhe_produto')
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/shop/models.py
from tkinter.tix import Tree
from django.db import models
from django.urls import reverse

class Categoria(models.Model):
    nome = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    
    class Meta:
        ordering = ('nome',)
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'
    def __str__(self) -> str:
        return self.nome
    
    def get_absolute_url(self):
        return reverse("shop:lista_produtos_categoria", args=[self.slug])
    


class Produto(models.Model):
    categoria = models.ForeignKey(Categoria, related_name='produtos',
                                  on_delete=models.CASCADE)
    nome = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    imagem = models.ImageField(upload_to='produtos/%Y/%m/%d', blank=True)
    descricao = models.TextField(blank=True)
    preco = models.DecimalField(max_digits=10,decimal_places=2)
    disponivel = models.BooleanField(default=True)
    criado = models.DateTimeField(auto_now_add=True)
    atualizado = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('nome',)
        index_together = (('id','slug'))
        
    def __str__(self) -> str:
        return self.nome
    
    def get_absolute_url(self):
        return reverse("shop:detalhe_produto", args=[self.id,self.slug])

myshop/cart/forms.py
from django import forms

QUANTIDADE_PRODUTOS_ESCOLHA = [(i,str(i)) for i in range(1,21)]

class AddProdutoCarrinhoForm(forms.Form):
    quantidade = forms.TypedChoiceField(
        choices=QUANTIDADE_PRODUTOS_ESCOLHA,
        coerce=int
    )
    sobrepor = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/cart/views.py
import django
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from shop.models import Produto
from .cart import Carrinho
from cart.forms import AddProdutoCarrinhoForm


# Create your views here.

@require_POST
def adiciona_carrinho(request, produto_id):
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, id =produto_id)
    form = AddProdutoCarrinhoForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        carrinho.add(produto=produto,
                     quantidade=cd['quantidade'],
                     substituir_quantidade=cd['sobrepor'])
    return redirect('cart:cart_detail')
    
@require_POST
def deleta_do_carrinho(request, produto_id):
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, id=produto_id)
    carrinho.remove(produto)
    return redirect('cart:cart_detail')

def carrinho_detail(request):
    carrinho = Carrinho(request)
    return render(request, 'cart/cart_detail.html', {'carrinho':carrinho})

myshop/shop/views.py
from django import forms
from django.shortcuts import render, get_object_or_404
from .models import Categoria, Produto
from cart.forms import AddProdutoCarrinhoForm
# Create your views here.

def lista_produtos(request, slug_categoria = None):
    categoria = None
    categorias = Categoria.objects.all()
    produtos = Produto.objects.filter(disponivel=True)
    if slug_categoria:
        categoria = get_object_or_404(Categoria, slug=slug_categoria)
        produtos = produtos.filter(categoria=categoria)
    return render(request, 'shop/list.html',
                  {'categoria':categoria,
                   'categorias': categorias,
                   'produtos':produtos})
    
def detalhe_produto(request, id, slug):
    produto = get_object_or_404(Produto,  slug=slug, disponivel=True)
    carrinho_produto_form = AddProdutoCarrinhoForm()
    return render(request, 'shop/detail.html', {'produto':produto,
                                                'carrinho_produto_form':carrinho_produto_form})

myshop/cart/templates/cart/cart_detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Seu carrinho de compras
{% endblock title %}

{% block content %}
  <h1>Seu Carrinho de Compras</h1>
  <table class="cart">
    <thead>
        <tr>
            <th>Imagem</th>
            <th>Produto</th>
            <th>Quantidade</th>
            <th>Remove</th>
            <th>Preço unitárip</th>
            <th>Preço</th>
        </tr>
    </thead>
    <tbody>
        {% for item  in carrinho %}
          {% with produto == item.produto  %}
            <tr>
                <td>
                    <a href="{{produto.get_absolute_url}}"><img src="
                        {% if produto.imagem %} {{produto.iamgem.url}}
                        {% else %}{% static 'img/no_image.png' %}{% endif %}" ></a>
                </td>
                <td>{{produto.nome}}</td>
                <td>{{item.quantidade}}</td>
                <td>
                    <form action="{% url 'cart:cart_remove' produto.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="remove">
                    </form>
                </td>
                <td class="num">${{item.preco}}</td>
                <td class="num">${{item.total_preco}}</td>
            </tr>
          {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">{{carrinho.get_total_preco}}</td>
        </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'shop:lista_produtos' %}" class="button-light">Continue Comprando</a>
    <a href="#" class="button">Checkout</a>
  </p>
{% endblock content %}

myshop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titulo %}My Shop{% endblock titulo %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <div id="header">
        <a class="logo" href="/">My Shop</a>
    </div>
    <div id="subheader">
        <div class="cart">
            Seu carro está vazio.
        </div>
    </div>
    <div id="content">
        {% block content %}
          
        {% endblock content %}
    </div>
</body>
    
</html>

myshop/shop/templates/shop/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block titulo %}
    {{produto.nome}}
{% endblock titulo %}

{% block content %}
  <div class="product-detail">
    <img src="{% if produto.imagem %}{{produto.imagem.url}}{% else %}
    {% static 'img/no_image.png' %}{% endif %}" >
    <h1>{{produto.nome}}</h1>
    <h2>
        <a href="{{produto.categoria.get_absolute_url}}">
            {{produto.categoria}}
        </a>
    </h2>
    <p class="price">
        {{produto.preco}}
    </p>
    <form action="{% url 'cart:cart_add' produto.id %}" method="post">
      {{carrinho_produto_form}}
      {% csrf_token %}
      <input type="submit" value="Adicionar ao Carrinho">
    </form>
    {{produto.descricao|linebreaks}}
  </div>
{% endblock content %}

myshop/shop/templates/shop/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block titulo %}
  {% if categoria %}
    {{categoria.nome}}
  {% else %}
    Produtos
  {% endif %}
{% endblock titulo %}

{% block content %}
   <div id="sidebar">
        <h3>Categorias</h3>
        <ul>
            <li {% if not categoria %} class="selected" {% endif %}>
                <a href="{% url 'shop:lista_produtos' %}">Todos</a>
            </li>
            {% for c in categorias %}
              <li {% if categoria.slug == c.slug %} class="selected"{% endif %}>
                <a href="{{ c.get_absolute_url }}">{{c.nome}}</a>
              </li>
            {% endfor %}
        </ul>
   </div>
   <div id="main" class="product-list">
        <h1>{% if categoria %}{{categoria.nome}}{% else %} Produtos {% endif %}</h1>
        {% for produto in produtos %}
            <div class="item">
                <a href="{{ produto.get_absolute_url }}">
                    <img src="{% if produto.imagem %}{{produto.imagem.url}}{% else %}
                    {% static 'img/no_image.png' %}{% endif %}"  alt="">
                </a>
                <a href="{{ produto.get_absolute_url }}">{{produto.nome}}</a>
                <br>
                ${{produto.preco}}
            </div>      
        {% endfor %}
   </div>
{% endblock content %} 